clubmaster/attendance/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^', views.attendance_view, name = "attendance_view")
]

clubmaster/clubmaster/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'clubmaster.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^attendance/', include('attendance.urls', namespace="attendance")),
    url(r'^', include('homepage.urls', namespace="homepage")),
    url(r'^admin/', include(admin.site.urls)),
]

clubmaster/homepage/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^home/$', views.user_registration, name = 'home'),
	url(r'^dashboard/$', views.dashboard, name = 'dashboard_home')
]

clubmaster/homepage/views.py
from django.shortcuts import render, redirect
from authentication.forms import UserRegistration, LoginForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.db import IntegrityError
from organizations.models import Organization




# def index(request):
#     """
#     A view that displays the homepage of the website
#     """
#     context = {}
#     return render(request, 'homepage/registration_template.html', context)


def user_registration(request):
    """
    A view for allowing users to register themselves or as an organization
    """
    title = 'Registration'
    

    form = UserRegistration(request.POST or None)
    login_form = LoginForm(request.POST or None)
    context = {
        'form':form,
        'login_form': login_form,
        'title':title
    }

    # print form.is_valid()
    if form.is_valid():
        """
        tests if an email has already been used
        """
        # print form.is_valid()
        if User.objects.filter(email=form.cleaned_data['email']).exists():  # tests for previously used emails
            error = "Email already in use"
            context = {
                'title': title,
                'error': error,
                'form': form
            }

        if form.cleaned_data['password'] != form.cleaned_data['confirm_password']:  # tests for non matching passowrds
            error = "Passwords don't match"
            context = {
                'title': title,
                'error': error,
                'form': form
            }

        if len(form.cleaned_data['password']) < 8:  # tests for too short passwords (less than 8 characters)
            error = "Password is too short, must be at least 8 characters"
            context = {
                'title': title,
                'error': error,
                'form': form
            }

        else:
            try:
                user = User.objects.create_user(  # create a new user object
                                                  email=form.cleaned_data['email'],
                                                  first_name=form.cleaned_data['first_name'],
                                                  last_name=form.cleaned_data['last_name'],
                                                  username=form.cleaned_data['email'],
                                                  # users use their emails as usernames by default
                                                  password=form.cleaned_data['password']
                                                  )
                print "user created"
                Organization(identifier=form.cleaned_data['org_name'], name =form.cleaned_data['org_name'], website = form.cleaned_data['website'], contact = form.cleaned_data['contact'], description = form.cleaned_data['description'], user=user).save()
                
            except IntegrityError:  # prevents a user from registering a previously used username
                error = 'Username already taken'
                context = {
                    'title': title,
                    'form': form,
                    'error': error
                }
                return render(request, 'homepage/registration_template.html', context)

            auth_user = authenticate(username=form.cleaned_data['email'], password=form.cleaned_data['password'])
            login(request, auth_user)
            return redirect('/dashboard/', context)
        return render(request, 'homepage/registration_template.html', context)
    if login_form.is_valid():
        auth_user = authenticate(username=form.cleaned_data['email'], password=form.cleaned_data['password'])
        login(request, auth_user)
        return redirect('/dashboard/', context)
    return render(request, 'homepage/registration_template.html', context)

def dashboard(request):
    context = {}
    return render(request, 'homepage/dashboard_home.html', context)

clubmaster/homepage/templates/homepage/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dashboard</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static "css/bootstrap.min.css"%}"rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "css/simple-sidebar.css"%}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- jQuery -->
    <script src="{% static "js/jquery.js"%}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "js/bootstrap.min.js"%}"></script>

</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        ClubMaster
                    </a>
                </li>
                <li>
                    <a href="{% url 'homepage:dashboard_home' %}">Dashboard</a>
                </li>
                <li>
                    <a href="{% url 'attendance:attendance_view' %}">Attendance</a>
                </li>
                <li>
                    <a href="#">Overview</a>
                </li>
                <li>
                    <a href="#">Events</a>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        {% block content %}
        {% endblock %}
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>

</html>

clubmaster/homepage/templates/homepage/dashboard_home.html
{% extends "homepage/dashboard.html" %}
{% block content %}

<div id="page-content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1>ClubMaster Dashboard</h1>
                <p>Hello! Welcome to your ClubMaster dashboard. Here you can view all your different tabs on the left. Click some to see where they go.</p>
                <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
            </div>
        </div>
    </div>
</div>


{% endblock %}

clubmaster/homepage/templates/homepage/index.html
<!DOCTYPE html>
<html lang="en">

<head>
	{% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>The ClubMaster</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" type="text/css">

    <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static "font-awesome/css/font-awesome.min.css" %}" type="text/css">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="{% static "css/animate.min.css" %}" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static "css/creative.css" %}" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">The ClubMaster</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#services">Services</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                    <li>
                        <a class="page-scroll" data-toggle="modal" data-target="#loginModal">Login</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1>Your Favorite Source of Club Management Software</h1>
                <hr>
                <p>The ClubMaster can help you manage your clubs better by centralizing your tools! Just login or register above!</p>
                <a href="#about" class="btn btn-primary btn-xl page-scroll">Find Out More</a>
            </div>
        </div>
    </header>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">We've got what you need!</h2>
                    <hr class="light">
                    <p class="text-faded">Clubmaster has everything you need to get your new club up and running in no time! Managing your club is now easier than ever!</p>
                    <button class="btn btn-default btn-xl" id="register" data-toggle="modal" data-target="#registrationModal">Get Started!</button>
                </div>
            </div>
        </div>
    </section>

    <div class="modal fade" id="registrationModal" tabindex="-1" role="dialog" aria-labelledby="Registration">
      <div class="modal-dialog" role="document">
        {% block registration %}{% endblock %}
      </div>
    </div>

    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="Login">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="login">Login Form</h4>
                    <h5>{{errors}}</h5>
                </div>
                <div class="modal-body">
                    <form method = 'POST', action = ''> 
                        {% csrf_token %} {{form.non_field_errors}}
                      <div class="form-group">
                        {{form.username.errors}}
                        <label for="{{form.id.username}}">Username (email):</label>
                        {{form.first_name}}
                      </div>
                      <div class="form-group">
                        {{form.last_name.errors}}
                        <label for="{{form.id.password}}" class="control-label">Password:</label>
                        {{form.last_name}}
                      </div>
                      <div class="form-group">
                        {{form.email.errors}}
                        <label for="{{form.id.org_name}}" class="control-label">Organization Name:</label>
                        {{form.email}}
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      <input type="submit" class="btn btn-primary"></input>
                      </div>
                    </form>
                </div>
            </div>  
        </div>
    </div>

    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">At Your Service</h2>
                    <hr class="primary">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-diamond wow bounceIn text-primary"></i>
                        <h3>Attendance Tracking</h3>
                        <p class="text-muted">Our app allows you to monitor club attendance.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-paper-plane wow bounceIn text-primary" data-wow-delay=".1s"></i>
                        <h3>Listserv Integration</h3>
                        <p class="text-muted">Send emails to the entire listserv or to different subgroups!</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-newspaper-o wow bounceIn text-primary" data-wow-delay=".2s"></i>
                        <h3>Financial Tracking</h3>
                        <p class="text-muted">Track club funds and assets and track trends over time.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-heart wow bounceIn text-primary" data-wow-delay=".3s"></i>
                        <h3>Love your Club</h3>
                        <p class="text-muted">Now you can love managing your club!</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="no-padding" id="portfolio">
        <div class="container-fluid">
            <div class="row no-gutter">            
            </div>
        </div>
    </section>

    <aside class="bg-dark">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="primary">
                    <p>Want to help us make Clubmaster better? That's great! Send us an email about what you think and we will take your ideas into consideration!</p>
                </div>
                <div class="col-lg-4 col-lg-offset-4 text-center">
                    <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                    <p><a href="mailto:your-email@your-domain.com">clubmaster@gmail.com</a></p>
                </div>
            </div>
        </div>
    </aside>

    <!-- jQuery -->
    <script src="{% static "js/jquery.js" %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "js/bootstrap.min.js"%}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static "js/jquery.easing.min.js"%}"></script>
    <script src="{% static "js/jquery.fittext.js"%}"></script>
    <script src="{% static "js/wow.min.js"%}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static "js/creative.js"%}"></script>

    <script type="text/javascript"> 
    $(document).ready(function() {
        //alert('hi');
        $('.modal').on('hidden.bs.modal', function(){
            $(this).find('form')[0].reset();
        });
     });
    </script>

</div>
</body>

</html>

clubmaster/homepage/templates/homepage/registration_template.html
{% extends "homepage/index.html" %}
{% block registration %}

<div class="modal-content">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="registration">Registration Form</h4>
    <h5>{{errors}}</h5>
  </div>
  <div class="modal-body">
    <form method = 'POST', action = ''> 
    	{% csrf_token %} {{form.non_field_errors}}
      <div class="form-group">
      	{{form.first_name.errors}}
        <label for="{{form.id.first_name}}">First Name:</label>
      	{{form.first_name}}
      </div>
      <div class="form-group">
        {{form.last_name.errors}}
        <label for="{{form.id.last_name}}" class="control-label">Last Name:</label>
        {{form.last_name}}
      </div>
      <div class="form-group">
        {{form.email.errors}}
        <label for="{{form.id.email}}" class="control-label">Email:</label>
        {{form.email}}
      </div>
      <div class="form-group">
        {{form.password.errors}}
        <label for="{{form.id.password}}" class="control-label">Password:</label>
        {{form.password}}
      </div>
      <div class="form-group">
        {{form.confirm_password.errors}}
        <label for="{{form.id.confirm_password}}" class="control-label">Confirm Password:</label>
        {{form.confirm_password}}
      </div>
      <div class="form-group">
  	    {{form.org_name.errors}}
        <label for="{{form.id.org_name}}" class="control-label">Organization Name:</label>
        {{form.org_name}}
	    </div>
  	  <div class="form-group">
  	    {{form.website.errors}}
        <label for="{{form.id.website}}" class="control-label">Website:</label>
        {{form.website}}
  	  </div>
  	  <div class="form-group">
  	    {{form.contact.errors}}
        <label for="{{form.id.contact}}" class="control-label">Contact Email:</label>
        {{form.contact}}
  	  </div>
  	  <div class="form-group">
  	    {{form.description.errors}}
        <label for="{{form.id.description}}" class="control-label">Club Description:</label>
        {{form.description}}        
  	  </div>
  	  <div class="form-group">
  	    {{form.logo.errors}}
        <label for="{{form.id.logo}}" class="control-label">Logo:</label>
        {{form.logo}}
  	  </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <input type="submit" class="btn btn-primary"></input>
      </div>
    </form>
  </div>
</div>

{% endblock %}